// Code generated by MockGen. DO NOT EDIT.
// Source: authentication.go

// Package authentication is a generated GoMock package.
package authentication

import (
	gomock "github.com/golang/mock/gomock"
)

// MockCallbackProvider is a mock of CallbackProvider interface.
type MockCallbackProvider struct {
	ctrl     *gomock.Controller
	recorder *MockCallbackProviderMockRecorder
}

// MockCallbackProviderMockRecorder is the mock recorder for MockCallbackProvider.
type MockCallbackProviderMockRecorder struct {
	mock *MockCallbackProvider
}

// NewMockCallbackProvider creates a new mock instance.
func NewMockCallbackProvider(ctrl *gomock.Controller) *MockCallbackProvider {
	mock := &MockCallbackProvider{ctrl: ctrl}
	mock.recorder = &MockCallbackProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCallbackProvider) EXPECT() *MockCallbackProviderMockRecorder {
	return m.recorder
}
